# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
  - npm ci

test:
  script:
    - npm run test:ci

coverage:
  script:
    - npm run coverage
  coverage: /Statements\s+:\s(\d+.?\d+)%/
  artifacts:
    when: always
    paths:
      # save coverage results
      - coverage
    expire_in: 10 days
